/* Hand-drawn SVG flags, ported verbatim from the lab mockup (banderas.js).
   No external images: most flags are stripes, generated by tiny helpers; the
   ones with artwork are simplified to what reads at ~18px wide. Keyed by the
   Spanish country names that `Player.nacionalidad` carries ("España",
   "Rumanía", "República Checa"…), accents and case ignored. */

const W = 30;
const H = 20;

/** Vertical stripes of equal width. */
function V(...colors: string[]): string {
  const a = W / colors.length;
  return colors.map((col, i) => `<rect x="${i * a}" y="0" width="${a}" height="${H}" fill="${col}"/>`).join('');
}

/** Horizontal stripes of equal height. */
function Hz(...colors: string[]): string {
  const a = H / colors.length;
  return colors.map((col, i) => `<rect x="0" y="${i * a}" width="${W}" height="${a}" fill="${col}"/>`).join('');
}

/** Horizontal stripes with weights: HW([['#c', 2], ['#d', 1]]). */
function HW(list: Array<[string, number]>): string {
  const tot = list.reduce((s, x) => s + x[1], 0);
  let y = 0;
  return list
    .map(([col, w]) => {
      const h = (H * w) / tot;
      const r = `<rect x="0" y="${y}" width="${W}" height="${h}" fill="${col}"/>`;
      y += h;
      return r;
    })
    .join('');
}

/** Nordic cross: background, cross and (optionally) an inner fillet. */
function nordica(fondo: string, cruz: string, filete?: string): string {
  let s =
    `<rect width="${W}" height="${H}" fill="${fondo}"/>` +
    `<rect x="0" y="7.5" width="${W}" height="5" fill="${cruz}"/>` +
    `<rect x="9" y="0" width="5" height="${H}" fill="${cruz}"/>`;
  if (filete) {
    s +=
      `<rect x="0" y="9" width="${W}" height="2" fill="${filete}"/>` +
      `<rect x="10.5" y="0" width="2" height="${H}" fill="${filete}"/>`;
  }
  return s;
}

function estrella(cx: number, cy: number, r: number, col: string): string {
  const p: string[] = [];
  for (let i = 0; i < 5; i++) {
    const a1 = Math.PI * (-0.5 + i * 0.4);
    const a2 = a1 + Math.PI * 0.2;
    p.push(`${(cx + r * Math.cos(a1)).toFixed(2)},${(cy + r * Math.sin(a1)).toFixed(2)}`);
    p.push(`${(cx + r * 0.42 * Math.cos(a2)).toFixed(2)},${(cy + r * 0.42 * Math.sin(a2)).toFixed(2)}`);
  }
  return `<polygon points="${p.join(' ')}" fill="${col}"/>`;
}

/** Lowercase, accents and non-letters stripped: "República Checa" → "republicacheca". */
export function normalizeCountry(name: string): string {
  return name
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z]/g, '');
}

const CATALOG: Record<string, string> = {
  espana: HW([['#AA151B', 1], ['#F1BF00', 2], ['#AA151B', 1]]),
  portugal:
    '<rect width="30" height="20" fill="#DA291C"/><rect width="12" height="20" fill="#046A38"/>' +
    '<circle cx="12" cy="10" r="4.2" fill="#FFE900" stroke="#046A38" stroke-width="1"/>',
  francia: V('#002395', '#ffffff', '#ED2939'),
  italia: V('#008C45', '#F4F5F0', '#CD212A'),
  alemania: Hz('#000000', '#DD0000', '#FFCE00'),
  paisesbajos: Hz('#AE1C28', '#ffffff', '#21468B'),
  belgica: V('#000000', '#FDDA24', '#EF3340'),
  inglaterra:
    '<rect width="30" height="20" fill="#ffffff"/><rect x="12" y="0" width="6" height="20" fill="#CE1124"/>' +
    '<rect x="0" y="7" width="30" height="6" fill="#CE1124"/>',
  escocia:
    '<rect width="30" height="20" fill="#005EB8"/>' +
    '<path d="M0 0 L30 20 M30 0 L0 20" stroke="#ffffff" stroke-width="4"/>',
  gales:
    '<rect width="30" height="10" fill="#ffffff"/><rect y="10" width="30" height="10" fill="#00AD43"/>' +
    '<path d="M10 11 q4 -5 9 -2 l3 -2 -1 3 3 1 -3 1 1 3 -4 -2 q-5 3 -8 -2Z" fill="#C8102E"/>',
  reinounido:
    '<rect width="30" height="20" fill="#012169"/>' +
    '<path d="M0 0 L30 20 M30 0 L0 20" stroke="#ffffff" stroke-width="4"/>' +
    '<path d="M0 0 L30 20 M30 0 L0 20" stroke="#C8102E" stroke-width="2"/>' +
    '<rect x="12" y="0" width="6" height="20" fill="#ffffff"/><rect x="0" y="7" width="30" height="6" fill="#ffffff"/>' +
    '<rect x="13" y="0" width="4" height="20" fill="#C8102E"/><rect x="0" y="8" width="30" height="4" fill="#C8102E"/>',
  irlanda: V('#169B62', '#ffffff', '#FF883E'),
  irlandadelnorte:
    '<rect width="30" height="20" fill="#ffffff"/><rect x="12" y="0" width="6" height="20" fill="#CE1124"/>' +
    '<rect x="0" y="7" width="30" height="6" fill="#CE1124"/>',
  suiza:
    '<rect width="30" height="20" fill="#D52B1E"/><rect x="13" y="4" width="4" height="12" fill="#ffffff"/>' +
    '<rect x="9" y="8" width="12" height="4" fill="#ffffff"/>',
  austria: Hz('#ED2939', '#ffffff', '#ED2939'),
  dinamarca: nordica('#C8102E', '#ffffff'),
  suecia: nordica('#006AA7', '#FECC00'),
  noruega: nordica('#BA0C2F', '#ffffff', '#00205B'),
  finlandia: nordica('#ffffff', '#003580'),
  islandia: nordica('#02529C', '#ffffff', '#DC1E35'),
  polonia: Hz('#ffffff', '#DC143C'),
  chequia:
    '<rect width="30" height="10" fill="#ffffff"/><rect y="10" width="30" height="10" fill="#D7141A"/>' +
    '<polygon points="0,0 13,10 0,20" fill="#11457E"/>',
  eslovaquia: Hz('#ffffff', '#0B4EA2', '#EE1C25'),
  hungria: Hz('#CE2939', '#ffffff', '#477050'),
  rumania: V('#002B7F', '#FCD116', '#CE1126'),
  bulgaria: Hz('#ffffff', '#00966E', '#D62612'),
  grecia:
    '<rect width="30" height="20" fill="#0D5EAF"/>' +
    '<rect y="2.2" width="30" height="2.2" fill="#ffffff"/><rect y="6.6" width="30" height="2.2" fill="#ffffff"/>' +
    '<rect y="11" width="30" height="2.2" fill="#ffffff"/><rect y="15.4" width="30" height="2.2" fill="#ffffff"/>' +
    '<rect width="11" height="11" fill="#0D5EAF"/><rect x="4.4" y="0" width="2.2" height="11" fill="#ffffff"/>' +
    '<rect x="0" y="4.4" width="11" height="2.2" fill="#ffffff"/>',
  turquia:
    '<rect width="30" height="20" fill="#E30A17"/>' +
    '<circle cx="12" cy="10" r="5" fill="#ffffff"/><circle cx="14" cy="10" r="4" fill="#E30A17"/>' +
    estrella(19, 10, 2.6, '#ffffff'),
  rusia: Hz('#ffffff', '#0039A6', '#D52B1E'),
  urss:
    '<rect width="30" height="20" fill="#CC0000"/>' +
    estrella(7, 5, 2.6, '#FFD700') +
    '<path d="M4 9 q3 3 6 1 q-2 4 -6 2Z" fill="#FFD700"/>',
  ucrania: Hz('#0057B7', '#FFD700'),
  serbia: Hz('#C6363C', '#0C4076', '#ffffff'),
  croacia:
    '<rect width="30" height="20" fill="#171796"/><rect width="30" height="6.6" fill="#FF0000"/>' +
    '<rect y="6.6" width="30" height="6.6" fill="#ffffff"/>' +
    '<rect x="12" y="6" width="6" height="6" fill="#FF0000"/><rect x="12" y="6" width="3" height="3" fill="#ffffff"/>' +
    '<rect x="15" y="9" width="3" height="3" fill="#ffffff"/>',
  eslovenia: Hz('#ffffff', '#0000C6', '#FF0000'),
  bosnia: '<rect width="30" height="20" fill="#002F6C"/><polygon points="9,0 24,0 9,20" fill="#FECB00"/>',
  yugoslavia: Hz('#0C4076', '#ffffff', '#C6363C'),
  montenegro:
    '<rect width="30" height="20" fill="#C40308"/>' +
    '<rect x="1.5" y="1" width="27" height="18" fill="none" stroke="#D4AF37" stroke-width="1.6"/>',
  macedonia:
    '<rect width="30" height="20" fill="#D20000"/>' +
    '<path d="M15 10 L0 0 M15 10 L30 0 M15 10 L0 20 M15 10 L30 20 M15 10 L0 10 M15 10 L30 10"' +
    ' stroke="#FFE600" stroke-width="2"/><circle cx="15" cy="10" r="4" fill="#FFE600"/>',
  albania:
    '<rect width="30" height="20" fill="#E41E20"/>' +
    '<path d="M11 6 l4 3 4 -3 -2 4 2 4 -4 -3 -4 3 2 -4Z" fill="#000000"/>',
  georgia:
    '<rect width="30" height="20" fill="#ffffff"/><rect x="12.5" y="0" width="5" height="20" fill="#FF0000"/>' +
    '<rect x="0" y="7.5" width="30" height="5" fill="#FF0000"/>',
  armenia: Hz('#D90012', '#0033A0', '#F2A800'),
  bielorrusia: HW([['#CE1720', 2], ['#007C30', 1]]),
  estonia: Hz('#0072CE', '#000000', '#ffffff'),
  letonia: HW([['#9E3039', 2], ['#ffffff', 1], ['#9E3039', 2]]),
  lituania: Hz('#FDB913', '#006A44', '#C1272D'),
  luxemburgo: Hz('#ED2939', '#ffffff', '#00A1DE'),
  malta: '<rect width="30" height="20" fill="#CF142B"/><rect width="15" height="20" fill="#ffffff"/>',
  chipre:
    '<rect width="30" height="20" fill="#ffffff"/><ellipse cx="15" cy="9" rx="6" ry="3.4" fill="#D57800"/>' +
    '<path d="M11 14 q4 3 8 0" stroke="#4E5B31" stroke-width="1.2" fill="none"/>',
  israel:
    '<rect width="30" height="20" fill="#ffffff"/><rect y="2.5" width="30" height="2.5" fill="#0038B8"/>' +
    '<rect y="15" width="30" height="2.5" fill="#0038B8"/>' +
    '<path d="M15 5.5 l3.6 6.3 h-7.2Z M15 14.5 l3.6 -6.3 h-7.2Z" fill="none" stroke="#0038B8" stroke-width="1.1"/>',

  brasil:
    '<rect width="30" height="20" fill="#009C3B"/><polygon points="15,2 28,10 15,18 2,10" fill="#FFDF00"/>' +
    '<circle cx="15" cy="10" r="4.2" fill="#002776"/>',
  argentina: Hz('#74ACDF', '#ffffff', '#74ACDF') + '<circle cx="15" cy="10" r="2.2" fill="#F6B40E"/>',
  uruguay:
    '<rect width="30" height="20" fill="#ffffff"/>' +
    '<rect x="11" y="2.2" width="19" height="2.2" fill="#0038A8"/><rect x="0" y="6.6" width="30" height="2.2" fill="#0038A8"/>' +
    '<rect x="0" y="11" width="30" height="2.2" fill="#0038A8"/><rect x="0" y="15.4" width="30" height="2.2" fill="#0038A8"/>' +
    '<circle cx="5.5" cy="4" r="2.6" fill="#FCD116"/>',
  paraguay: Hz('#D52B1E', '#ffffff', '#0038A8'),
  chile:
    '<rect width="30" height="20" fill="#ffffff"/><rect y="10" width="30" height="10" fill="#D52B1E"/>' +
    '<rect width="10" height="10" fill="#0039A6"/>' +
    estrella(5, 5, 3, '#ffffff'),
  colombia: HW([['#FCD116', 2], ['#003893', 1], ['#CE1126', 1]]),
  peru: V('#D91023', '#ffffff', '#D91023'),
  ecuador: HW([['#FFDD00', 2], ['#0033A0', 1], ['#EF3340', 1]]),
  bolivia: Hz('#D52B1E', '#F9E300', '#007A33'),
  venezuela: Hz('#FFCC00', '#00247D', '#CF142B'),
  mexico: V('#006847', '#ffffff', '#CE1126'),
  estadosunidos:
    '<rect width="30" height="20" fill="#ffffff"/>' +
    '<rect y="0" width="30" height="3" fill="#B22234"/><rect y="6" width="30" height="3" fill="#B22234"/>' +
    '<rect y="12" width="30" height="3" fill="#B22234"/><rect y="18" width="30" height="2" fill="#B22234"/>' +
    '<rect width="13" height="11" fill="#3C3B6E"/>' +
    estrella(6.5, 5.5, 3, '#ffffff'),
  costarica: HW([['#002B7F', 1], ['#ffffff', 1], ['#CE1126', 2], ['#ffffff', 1], ['#002B7F', 1]]),
  honduras: Hz('#0073CF', '#ffffff', '#0073CF'),

  marruecos:
    '<rect width="30" height="20" fill="#C1272D"/>' +
    '<path d="M15 5 l3.2 9.8 -8.3 -6h10.2l-8.3 6Z" fill="none" stroke="#006233" stroke-width="1.2"/>',
  argelia:
    '<rect width="30" height="20" fill="#006233"/><rect x="15" width="15" height="20" fill="#ffffff"/>' +
    '<circle cx="15" cy="10" r="5" fill="#D21034"/><circle cx="17" cy="10" r="4" fill="#ffffff"/>' +
    estrella(20.5, 10, 2.4, '#D21034'),
  tunez:
    '<rect width="30" height="20" fill="#E70013"/><circle cx="15" cy="10" r="5.5" fill="#ffffff"/>' +
    '<circle cx="15" cy="10" r="3.8" fill="#E70013"/><circle cx="16.4" cy="10" r="3" fill="#ffffff"/>' +
    estrella(17.6, 10, 1.9, '#E70013'),
  egipto: Hz('#CE1126', '#ffffff', '#000000'),
  nigeria: V('#008751', '#ffffff', '#008751'),
  camerun: V('#007A5E', '#CE1126', '#FCD116') + estrella(15, 10, 2.4, '#FCD116'),
  senegal: V('#00853F', '#FDEF42', '#E31B23') + estrella(15, 10, 2.6, '#00853F'),
  costademarfil: V('#F77F00', '#ffffff', '#009E60'),
  ghana: Hz('#CE1126', '#FCD116', '#006B3F') + estrella(15, 10, 2.4, '#000000'),
  guinea: V('#CE1126', '#FCD116', '#009460'),
  mali: V('#14B53A', '#FCD116', '#CE1126'),
  sudafrica:
    '<rect width="30" height="20" fill="#002395"/><rect width="30" height="10" fill="#DE3831"/>' +
    '<rect x="0" y="8.5" width="30" height="3" fill="#007A4D"/>' +
    '<path d="M0 0 L14 10 L0 20Z" fill="#007A4D" stroke="#ffffff" stroke-width="1.4"/>',
  angola:
    '<rect width="30" height="20" fill="#000000"/><rect width="30" height="10" fill="#CE1126"/>' +
    estrella(15, 10, 2.6, '#FFCB00'),
  caboverde:
    '<rect width="30" height="20" fill="#003893"/><rect y="11" width="30" height="4" fill="#ffffff"/>' +
    '<rect y="12.4" width="30" height="1.2" fill="#CF2027"/>',
  congo: V('#009543', '#FBDE4A', '#DC241F'),
  rdcongo:
    '<rect width="30" height="20" fill="#007FFF"/><path d="M0 16 L26 0 h4 v4 L4 20Z" fill="#F7D618"/>' +
    estrella(5, 4, 2.4, '#F7D618'),
  togo:
    Hz('#006A4E', '#FFCE00', '#006A4E', '#FFCE00', '#006A4E') +
    '<rect width="12" height="12" fill="#D21034"/>' +
    estrella(6, 6, 3, '#ffffff'),
  burkinafaso: Hz('#EF2B2D', '#009E49') + estrella(15, 10, 2.8, '#FCD116'),
  gabon: Hz('#009E60', '#FCD116', '#3A75C4'),

  japon: '<rect width="30" height="20" fill="#ffffff"/><circle cx="15" cy="10" r="5.5" fill="#BC002D"/>',
  coreadelsur:
    '<rect width="30" height="20" fill="#ffffff"/><circle cx="15" cy="10" r="5" fill="#CD2E3A"/>' +
    '<path d="M10 10 a2.5 2.5 0 0 1 5 0 a2.5 2.5 0 0 0 5 0 a5 5 0 0 0 -10 0Z" fill="#0047A0"/>',
  china:
    '<rect width="30" height="20" fill="#EE1C25"/>' +
    estrella(6, 5, 3, '#FFFF00') +
    estrella(12, 2.5, 1.3, '#FFFF00') +
    estrella(14, 5.5, 1.3, '#FFFF00') +
    estrella(12, 9, 1.3, '#FFFF00'),
  australia:
    '<rect width="30" height="20" fill="#00008B"/>' +
    '<path d="M0 0 L14 9 M14 0 L0 9" stroke="#ffffff" stroke-width="2"/>' +
    '<rect x="6" y="0" width="2.5" height="9" fill="#ffffff"/><rect x="0" y="3.2" width="14" height="2.5" fill="#ffffff"/>' +
    '<rect x="6.5" y="0" width="1.5" height="9" fill="#C8102E"/><rect x="0" y="3.7" width="14" height="1.5" fill="#C8102E"/>' +
    estrella(22, 12, 2.6, '#ffffff') +
    estrella(7, 15, 2, '#ffffff'),
  iran: Hz('#239F40', '#ffffff', '#DA0000'),
  arabiasaudi:
    '<rect width="30" height="20" fill="#006C35"/><rect x="5" y="13" width="20" height="1.6" fill="#ffffff"/>' +
    '<rect x="6" y="6" width="18" height="1.6" fill="#ffffff"/>',
};

// Alternate names the data brings.
CATALOG.holanda = CATALOG.paisesbajos!;
CATALOG.unionsovietica = CATALOG.urss!;
CATALOG.granbretana = CATALOG.reinounido!;
CATALOG.eeuu = CATALOG.estadosunidos!;
CATALOG.usa = CATALOG.estadosunidos!;
CATALOG.corea = CATALOG.coreadelsur!;
CATALOG.republicacheca = CATALOG.chequia!;
CATALOG.checoslovaquia = CATALOG.chequia!;
CATALOG.serbiaymontenegro = CATALOG.yugoslavia!;
CATALOG.alemaniafederal = CATALOG.alemania!;
CATALOG.alemaniaoriental = CATALOG.alemania!;

/** Whether a drawn flag exists for this country name. */
export function hasFlag(country: string | null | undefined): boolean {
  return country != null && normalizeCountry(country) in CATALOG;
}

interface FlagProps {
  /** Country name as the data carries it ("España", "República Checa"…). */
  country: string | null | undefined;
  className?: string;
}

/**
 * Little flag for the country, or a steel plate with its two initials when we
 * have no drawing (or no nationality at all).
 */
export function Flag({ country, className }: FlagProps) {
  const name = country ?? '';
  const body = name ? CATALOG[normalizeCountry(name)] : undefined;
  const cls = className ? `bandera ${className}` : 'bandera';
  return (
    <svg className={cls} viewBox="0 0 30 20" role="img" aria-label={name || 'Sin nacionalidad'}>
      <title>{name || 'Sin nacionalidad'}</title>
      {body ? (
        <g dangerouslySetInnerHTML={{ __html: body }} />
      ) : (
        <>
          <rect width="30" height="20" fill="#2A4478" />
          <text x="15" y="14.5" textAnchor="middle" fontFamily="sans-serif" fontSize="11" fill="#B8C8E8">
            {(name || '?').slice(0, 2).toUpperCase()}
          </text>
        </>
      )}
      <rect x=".5" y=".5" width="29" height="19" fill="none" stroke="rgba(0,0,0,.45)" />
    </svg>
  );
}
