import type { Player, TeamColors } from '@data';
import type { Formation, Pichichi, Zamora } from '@engine';
import type { SeasonState } from '../season/season';
import type { Division } from './promotion';
import type { BoardState } from './board';
import type { ConfianzaState } from './confianza';
import type { Contract } from './contracts';
import type { RenewalsState } from './renewals';
import type { CopaResult } from '../tournament/copa';
import type { EuropaResult } from './europa';
import type { TrainingState } from './training';
import type { StadiumState } from './stadium';
import type { SponsorState } from './sponsors';
import type { CreditState } from './credit';
import type { LoansState } from './loans';
import type { HemerotecaEvent } from './hemeroteca';
import type { WinterMarketState } from './winterMovements';
import type { StaffState } from './staff';

/** The human's chosen tactics, stored by player id so it survives evolution. */
export interface CareerTactics {
  formation: Formation;
  /** Chosen starting XI as player ids; when absent the best XI is auto-picked. */
  xiIds?: string[];
}

/** A team as it lives across a career: full player data that evolves season to season. */
export interface CareerTeam {
  id: string;
  nombre: string;
  colores?: TeamColors;
  players: Player[];
}

/**
 * A youth-academy prospect: a young player (16-18) generated by your club each
 * pretemporada with LOW current attributes but a HIDDEN potential ceiling
 * (`player.potencial`). It lives in the cantera until you PROMOTE it to the first
 * team or it leaves for not making the grade. `entrySeason` is the career season
 * it was generated in, which drives how long the scout has observed it.
 */
export interface YouthProspect {
  player: Player;
  /** 1-indexed career season this prospect entered the academy. */
  entrySeason: number;
}

/**
 * A rival-scouting record for one player: how deeply the human has ojeado them.
 * It is the human's DECISION (which rivals to assign a scout to), so it is
 * persisted in the save. Keyed by player id in `CareerState.scouting`.
 */
export interface ScoutingRecord {
  /** Total scouting assignments made on this player (accumulates across seasons). */
  observations: number;
  /** Last career season a scout was assigned to this player (1-indexed; 0 = never). */
  lastSeason: number;
}

/**
 * A "seguimiento" of a rival PROMESA: the human DECISION to follow a young talent
 * from another club so their fallible potential band narrows the longer you watch.
 * It is your decision (not derivable from replay), so it is persisted in the save.
 * Keyed by player id in `CareerState.prospectTracking`.
 */
export interface ProspectTracking {
  /**
   * 1-indexed career season you STARTED following this prospect. How many seasons
   * you have observed them (which tightens the band) is `seasonNumber - since`.
   */
  since: number;
}

/** One line of the career league-champions roll. Grows with retirements/transfers later. */
export interface SeasonSummary {
  seasonNumber: number;
  temporada: string;
  championId: string;
  /** The division the human competed in that season (for Europe qualification). */
  division?: Division;
  /** The human's final league position that season, 1-indexed (for Europe qualification). */
  humanPosition?: number;
  /** Season top scorer (Pichichi). Absent in pre-trophies saves/seasons. */
  pichichi?: Pichichi;
  /** Season least-conceded keeper (Zamora). Absent in pre-trophies saves/seasons. */
  zamora?: Zamora;
}

/**
 * A competition the human club can win, for the palmarés. `liga` is the human's
 * own division title (Primera or Segunda — see `PalmaresTitle.division`); the
 * others are the domestic cup and the two continental cups.
 */
export type TitleCompetition = 'liga' | 'copa' | 'champions' | 'uefa';

/**
 * One title in the club's palmarés: which competition, and in which season it was
 * won. For a league title, `division` records which division was won so the UI
 * can tell a Primera title from a Segunda one.
 */
export interface PalmaresTitle {
  competition: TitleCompetition;
  /** 1-indexed career season the title was won in. */
  seasonNumber: number;
  /** Season label, e.g. "96/97". */
  temporada: string;
  /** For a league title, the division that was won. */
  division?: Division;
}

/**
 * One recorded press-conference decision: which question was put to the manager
 * and the option they chose, tied to the matchday it was answered at.
 *
 * This is a PLAYER DECISION — like tactics or the retain list, it is NOT derivable
 * by replaying the season's results — so it is persisted and re-applied
 * deterministically on load (see pressConference.ts). Keyed by matchday so a load
 * can interleave each morale effect at the exact point it was taken.
 */
export interface PressAnswer {
  /** career.season.currentMatchday at the moment the manager answered. */
  matchday: number;
  questionId: string;
  optionId: string;
}

/** The season's press-conference decisions, oldest first. Resets each season. */
export interface PressState {
  answers: PressAnswer[];
}

/**
 * The whole career: owner of the evolving full-data teams. The in-progress
 * `season` is DERIVED from `teams`; the teams are the source of truth.
 */
export interface CareerState {
  seed: number;
  leagueId: string;
  humanTeamId: string;
  /** 1-indexed career season. */
  seasonNumber: number;
  /** Season label, e.g. "96/97". */
  temporada: string;
  pointsForWin: 2 | 3;
  relegationSpots: number;
  /** Which division the human currently competes in. */
  division: Division;
  /** The board relationship: this season's objective and last season's verdict. */
  board: BoardState;
  /**
   * The two institutional confidence meters (directiva + afición), an EVOLVING
   * value that accumulates across seasons. Optional so pre-confianza saves and the
   * many places that build a career meta stay valid; absent means the neutral
   * default (see DEFAULT_CONFIANZA). Never re-derived inside `seasonFromCareer`:
   * it is updated at each season transition and carried forward.
   */
  confianza?: ConfianzaState;
  /**
   * This season's press-conference decisions. Optional so pre-rueda saves and the
   * many places that build a career meta stay valid; absent means "no answers yet".
   */
  press?: PressState;
  /** The human's tactics for their matches; absent means neutral auto-XI. */
  tactics?: CareerTactics;
  /** The season's training focus for the human club; absent means the default (equilibrado). */
  training?: TrainingState;
  /** This season's Copa del Rey (regenerated deterministically; not persisted). */
  copa?: CopaResult;
  /** This season's European competition (regenerated deterministically; not persisted). */
  europa?: EuropaResult;
  /** The human club's transfer budget, in whole euros. */
  budget: number;
  /** The human club's stadium: its aforo/expansion level (drives gate income). */
  stadium: StadiumState;
  /**
   * The club's chosen main sponsor (a player DECISION → persisted in save v2).
   * Optional so pre-patrocinios saves and the many places that build a career
   * meta stay valid; absent means the basic sponsor (see DEFAULT_SPONSOR).
   */
  sponsor?: SponsorState;
  /**
   * The club's bank/board CREDIT and DEUDA state (loan owed + seasons over the
   * credit limit). A negative `budget` above is the visible "números rojos"; this
   * tracks the loan on top and the sacking counter. Optional so pre-crédito saves
   * and every place that builds a career meta stay valid; absent means debt-free
   * (see DEFAULT_CREDIT). Persisted in save v2.
   */
  credit?: CreditState;
  /**
   * The club's loan book: players sent OUT on loan (returning next season) and
   * players brought IN on loan this season. A player DECISION → persisted in save
   * v2. Optional so pre-cesiones saves and the many places that build a career
   * meta stay valid; absent means an empty loan book (see DEFAULT_LOANS).
   */
  loans?: LoansState;
  /**
   * The mid-season WINTER TRANSFER WINDOW: the movements made at the season's
   * midpoint (which drive the season derivation — see winterMovements.ts) and
   * whether it has been closed this season. A player DECISION → persisted in save
   * v2. Optional so pre-invierno saves and every place that builds a career meta
   * stay valid; absent means an untouched window (see DEFAULT_WINTER). Because the
   * movements are how the derivation reconstructs the first/second halves, `teams`
   * stays the CURRENT (post-winter) squad and is never itself rewound.
   */
  winter?: WinterMarketState;
  /**
   * The club's technical STAFF (segundo entrenador, preparador físico, médico,
   * ojeador), each an optional hired member with a level. A player DECISION →
   * persisted in save v2. Optional so pre-staff saves and the many places that
   * build a career meta stay valid; absent means no staff hired (see DEFAULT_STAFF).
   * Each hired role feeds a bonus into an existing system and its salary into the
   * season liquidation (see staff.ts).
   */
  staff?: StaffState;
  teams: CareerTeam[];
  /**
   * The club's hemeroteca: a chronological archive of the career's HITOS as press
   * headlines (titles, ascensos/descensos, tus Pichichi/Zamora, retiradas de
   * cracks, fichajes récord, veredictos de la directiva). Appended to at the
   * season transition and at record transfers (see hemeroteca.ts). Optional so
   * pre-hemeroteca saves and the many places that build a career meta stay valid;
   * absent means an empty archive.
   */
  hemeroteca?: HemerotecaEvent[];
  /**
   * Your squad's contracts (salario + años), keyed by player id. Only the human
   * club's players are tracked, since only your masa salarial is charged against
   * the budget. See contracts.ts.
   */
  contracts: Record<string, Contract>;
  /**
   * This season's contract RENEWALS: the manager's decisions on players whose
   * deal is in its final year (renew on new terms, or let them leave FREE). A
   * player DECISION → persisted in save v2; reset each transition. Optional so
   * pre-renovaciones saves and every place that builds a career meta stay valid;
   * absent means no negotiations resolved yet (see DEFAULT_RENEWALS).
   */
  renewals?: RenewalsState;
  /** Your club's youth-academy prospects awaiting promotion (see YouthProspect). */
  youthProspects: YouthProspect[];
  /**
   * Your scouting reports on RIVAL players, keyed by player id. Records how many
   * times (and when) you have ojeado each one, so the fallible report narrows the
   * more you observe. A human DECISION → persisted in save v2 (empty by default).
   */
  scouting: Record<string, ScoutingRecord>;
  /**
   * Your "seguimiento" of rival PROMESAS, keyed by player id: which young talents
   * from other clubs you follow, and since when, so their fallible potential band
   * narrows the longer you track them (see prospects.ts). A human DECISION →
   * persisted in save v2 (empty by default). Distinct from `scouting`, which is the
   * per-season ojeo of ANY rival; this is the follow-list of curated youngsters.
   */
  prospectTracking: Record<string, ProspectTracking>;
  season: SeasonState;
  history: SeasonSummary[];
  /**
   * The club's palmarés: every title the human has won across the career, in the
   * order they were won. Appended to at each season transition (see palmares.ts).
   */
  palmares: PalmaresTitle[];
}
