import type { Player, TeamColors } from '@data';
import type { Formation } from '@engine';
import type { SeasonState } from '../season/season';
import type { Division } from './promotion';
import type { BoardState } from './board';
import type { Contract } from './contracts';
import type { CopaResult } from '../tournament/copa';
import type { EuropaResult } from './europa';
import type { TrainingState } from './training';

/** The human's chosen tactics, stored by player id so it survives evolution. */
export interface CareerTactics {
  formation: Formation;
  /** Chosen starting XI as player ids; when absent the best XI is auto-picked. */
  xiIds?: string[];
}

/** A team as it lives across a career: full player data that evolves season to season. */
export interface CareerTeam {
  id: string;
  nombre: string;
  colores?: TeamColors;
  players: Player[];
}

/**
 * A youth-academy prospect: a young player (16-18) generated by your club each
 * pretemporada with LOW current attributes but a HIDDEN potential ceiling
 * (`player.potencial`). It lives in the cantera until you PROMOTE it to the first
 * team or it leaves for not making the grade. `entrySeason` is the career season
 * it was generated in, which drives how long the scout has observed it.
 */
export interface YouthProspect {
  player: Player;
  /** 1-indexed career season this prospect entered the academy. */
  entrySeason: number;
}

/** One line of the career league-champions roll. Grows with retirements/transfers later. */
export interface SeasonSummary {
  seasonNumber: number;
  temporada: string;
  championId: string;
  /** The division the human competed in that season (for Europe qualification). */
  division?: Division;
  /** The human's final league position that season, 1-indexed (for Europe qualification). */
  humanPosition?: number;
}

/**
 * A competition the human club can win, for the palmarés. `liga` is the human's
 * own division title (Primera or Segunda — see `PalmaresTitle.division`); the
 * others are the domestic cup and the two continental cups.
 */
export type TitleCompetition = 'liga' | 'copa' | 'champions' | 'uefa';

/**
 * One title in the club's palmarés: which competition, and in which season it was
 * won. For a league title, `division` records which division was won so the UI
 * can tell a Primera title from a Segunda one.
 */
export interface PalmaresTitle {
  competition: TitleCompetition;
  /** 1-indexed career season the title was won in. */
  seasonNumber: number;
  /** Season label, e.g. "96/97". */
  temporada: string;
  /** For a league title, the division that was won. */
  division?: Division;
}

/**
 * The whole career: owner of the evolving full-data teams. The in-progress
 * `season` is DERIVED from `teams`; the teams are the source of truth.
 */
export interface CareerState {
  seed: number;
  leagueId: string;
  humanTeamId: string;
  /** 1-indexed career season. */
  seasonNumber: number;
  /** Season label, e.g. "96/97". */
  temporada: string;
  pointsForWin: 2 | 3;
  relegationSpots: number;
  /** Which division the human currently competes in. */
  division: Division;
  /** The board relationship: this season's objective and last season's verdict. */
  board: BoardState;
  /** The human's tactics for their matches; absent means neutral auto-XI. */
  tactics?: CareerTactics;
  /** The season's training focus for the human club; absent means the default (equilibrado). */
  training?: TrainingState;
  /** This season's Copa del Rey (regenerated deterministically; not persisted). */
  copa?: CopaResult;
  /** This season's European competition (regenerated deterministically; not persisted). */
  europa?: EuropaResult;
  /** The human club's transfer budget, in whole euros. */
  budget: number;
  teams: CareerTeam[];
  /**
   * Your squad's contracts (salario + años), keyed by player id. Only the human
   * club's players are tracked, since only your masa salarial is charged against
   * the budget. See contracts.ts.
   */
  contracts: Record<string, Contract>;
  /** Your club's youth-academy prospects awaiting promotion (see YouthProspect). */
  youthProspects: YouthProspect[];
  season: SeasonState;
  history: SeasonSummary[];
  /**
   * The club's palmarés: every title the human has won across the career, in the
   * order they were won. Appended to at each season transition (see palmares.ts).
   */
  palmares: PalmaresTitle[];
}
