/** Screens of the minimal retro shell. */
export type Screen =
  | 'title'
  | 'newGame'
  | 'teamSelect'
  | 'season'
  | 'prematch'
  | 'seasonEnd'
  | 'market'
  | 'squad'
  | 'youth'
  | 'ojeo'
  | 'tactics'
  | 'training'
  | 'stadium'
  | 'tournament'
  | 'copa'
  | 'europa'
  | 'palmares'
  | 'press'
  | 'match'
  | 'slots';
